def fetch_duration(self, file_path: Path): ...
class NowPlaying(Static):
    def on_mount(self) -> None: ...
    def _tick(self) -> None: ...
    def on_now_playing_message(self, message: 'NowPlayingMessage') -> None: ...
    def _fmt_mmss(self, seconds: float | None) -> str: ...
    def _marquee(self, width: int | None = None) -> str: ...
    def render(self) -> str: ...

class NowPlayingMessage(Message):
    def __init__(self, sender, title: str, source: str, state: str): ...

class ProgressBar(Static):
    def _fmt_mmss(self, seconds: float | None) -> str: ...
    def render(self) -> str: ...

class VolumeIndicator(Static):
    def render(self) -> str: ...

class MusicPlayerApp(App):
    def __init__(self): ...
    def compose(self) -> ComposeResult: ...
    async def on_mount(self) -> None: ...
    def update_volume_ui(self): ...
    def action_volume_up(self): ...
    def action_volume_down(self): ...
    def action_toggle_mute(self): ...
    def fmt_mmss(self, seconds: float | None) -> str: ...
    async def load_stations(self, path: Path): ...
    async def on_radio_set_changed(self, event): ...
    async def load_local_files(self, path: Path): ...
    async def load_m3u(self, path: Path): ...
    async def on_button_pressed(self, event: Button.Pressed) -> None: ...
    async def on_list_view_selected(self, event: ListView.Selected) -> None: ...
    async def on_directory_tree_file_selected(self, event: DirectoryTree.FileSelected) -> None: ...
    async def load_stations_ui(self): ...
    def update_now_playing(self, title: str, source: str, state: str): ...
    def _refresh_metadata(self): ...
    def update_progress(self): ...
    def action_toggle_play(self): ...
    def action_play(self): ...
    def action_pause(self): ...
    def action_stop(self): ...
    def action_seek_forward(self): ...
    def action_seek_backward(self): ...
    def _seek_to_percent(self, percent: float): ...
    def action_seek_to_10(self): ...
    def action_seek_to_50(self): ...
    def action_seek_to_90(self): ...
    async def play_station(self, station, idx): ...
    def play_local(self, path): ...
    def action_play_playlist(self) -> None: ...
